import numpy as np
import matplotlib.pyplot as plt
from scipy import signal

# System parameters
m1 = 1033.0
m2 = 500.0
L = 20.0
bx = 820.0
btheta = 2795.0
g = 9.81

Ka = 5200.0
tau1 = 0.270
tau2 = 0.010

mtot = m1 + m2

# Coefficients of the crane transfer function
a3 = m1 * m2 * L**2
a2 = bx * m2 * L**2 + btheta * mtot
a1 = m2 * g * L * mtot + bx * btheta
a0 = m2 * bx * g * L

# Crane transfer function Gc(s) = Xb(s) / F(s)
crane_num = np.array([btheta, m2 * g * L])
crane_den = np.array([a3, a2, a1, a0, 0.0])

# Actuator transfer function Ga(s) = F(s) / V(s)
actuator_num = np.array([Ka])
actuator_den = np.polymul([tau1, 1.0], [tau2, 1.0])

# Complete plant Gp(s) = Ga(s)Gc(s)
plant_num = np.polymul(actuator_num, crane_num)
plant_den = np.polymul(actuator_den, crane_den)

# Initial PID gains
Kp = 0.02
Ki = 0.0001
Kd = 0.01

# PID transfer function: Kd*s^2 + Kp*s + Ki over s
pid_num = np.array([Kd, Kp, Ki])
pid_den = np.array([1.0, 0.0])

# Open-loop transfer function
open_num = np.polymul(pid_num, plant_num)
open_den = np.polymul(pid_den, plant_den)

# Closed-loop transfer function with unity feedback
closed_num = open_num
closed_den = np.polyadd(open_den, open_num)

# Closed-loop poles
poles = np.roots(closed_den)

print("Closed-loop poles:")
print(poles)

if np.all(np.real(poles) < 0):
    print("The closed-loop system is stable.")
else:
    print("The closed-loop system is unstable.")

# Step response
reference = 20.0
t = np.linspace(0, 300, 3000)

system = signal.TransferFunction(closed_num, closed_den)
t, y_unit = signal.step(system, T=t)

y = reference * y_unit

# Metrics
maximum_value = np.max(y)
overshoot = (maximum_value - reference) / reference * 100

tolerance = 0.02 * abs(reference)
within_band = np.abs(y - reference) <= tolerance
outside_indices = np.where(~within_band)[0]

if len(outside_indices) == 0:
    settling_time = 0.0
elif outside_indices[-1] + 1 < len(t):
    settling_time = t[outside_indices[-1] + 1]
else:
    settling_time = np.nan

steady_state_error = reference - y[-1]

print(f"Overshoot: {overshoot:.2f} %")
print(f"Settling time: {settling_time:.2f} s")
print(f"Steady-state error: {steady_state_error:.4f} m")

# Plot
plt.figure(figsize=(7, 4))
plt.plot(t, y, label="Hook position x_B")
plt.axhline(reference, linestyle="--", label="Reference")
plt.xlabel("Time (s)")
plt.ylabel("Hook position x_B (m)")
plt.title("Linear closed-loop step response")
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.savefig("linear_step_response.png", dpi=300)
plt.show()
# ------------------------------------------------------------
# Nonlinear simulation of the original crane dynamics
# ------------------------------------------------------------
from scipy.integrate import solve_ivp

def nonlinear_crane_dynamics(t, state):
    # State vector
    # state[0] = xA
    # state[1] = xA_dot
    # state[2] = theta
    # state[3] = theta_dot
    # state[4] = integral of tracking error
    # state[5] = actuator first state
    # state[6] = actuator second state

    xA = state[0]
    xA_dot = state[1]
    theta = state[2]
    theta_dot = state[3]
    error_integral = state[4]
    actuator_1 = state[5]
    actuator_2 = state[6]

    # Hook position and velocity
    xB = xA + L * np.sin(theta)
    xB_dot = xA_dot + L * np.cos(theta) * theta_dot

    # Tracking error
    error = reference - xB
    error_dot = -xB_dot

    # PID controller output voltage
    voltage = Kp * error + Ki * error_integral + Kd * error_dot

    # Actuator dynamics
    actuator_1_dot = (voltage - actuator_1) / tau1
    actuator_2_dot = (actuator_1 - actuator_2) / tau2

    # Force generated by actuator
    F = Ka * actuator_2

    # Nonlinear crane equations written as a 2 by 2 system
    M = np.array([
        [mtot, m2 * L * np.cos(theta)],
        [m2 * L * np.cos(theta), m2 * L**2]
    ])

    rhs = np.array([
        F - bx * xA_dot + m2 * L * theta_dot**2 * np.sin(theta),
        -btheta * theta_dot - m2 * g * L * np.sin(theta)
    ])

    accelerations = np.linalg.solve(M, rhs)

    xA_ddot = accelerations[0]
    theta_ddot = accelerations[1]

    return [
        xA_dot,
        xA_ddot,
        theta_dot,
        theta_ddot,
        error,
        actuator_1_dot,
        actuator_2_dot
    ]


# Initial conditions
initial_state = [
    0.0,    # xA
    0.0,    # xA_dot
    0.0,    # theta
    0.0,    # theta_dot
    0.0,    # integral of error
    0.0,    # actuator first state
    0.0     # actuator second state
]

# Time span
t_start = 0.0
t_end = 300.0
t_eval = np.linspace(t_start, t_end, 3000)

solution = solve_ivp(
    nonlinear_crane_dynamics,
    [t_start, t_end],
    initial_state,
    t_eval=t_eval,
    rtol=1e-6,
    atol=1e-8
)

t_nl = solution.t
xA_nl = solution.y[0]
theta_nl = solution.y[2]
xB_nl = xA_nl + L * np.sin(theta_nl)

theta_deg = theta_nl * 180.0 / np.pi
max_swing_angle = np.max(np.abs(theta_deg))

print(f"Maximum swing angle: {max_swing_angle:.2f} deg")
print(f"Final nonlinear hook position: {xB_nl[-1]:.4f} m")
print(f"Final nonlinear trolley position: {xA_nl[-1]:.4f} m")


# Plot nonlinear xA and xB
plt.figure(figsize=(7, 4))
plt.plot(t_nl, xA_nl, label="Trolley position x_A")
plt.plot(t_nl, xB_nl, label="Hook position x_B")
plt.axhline(reference, linestyle="--", label="Reference")
plt.xlabel("Time (s)")
plt.ylabel("Position (m)")
plt.title("Nonlinear closed-loop position response")
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.savefig("nonlinear_position_response.png", dpi=300)
plt.show()


# Plot nonlinear swing angle
plt.figure(figsize=(7, 4))
plt.plot(t_nl, theta_deg, label="Swing angle theta")
plt.xlabel("Time (s)")
plt.ylabel("Swing angle theta (deg)")
plt.title("Nonlinear swing angle response")
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.savefig("nonlinear_swing_angle.png", dpi=300)
plt.show()
# ------------------------------------------------------------
# Robustness test for different payload masses
# ------------------------------------------------------------

def simulate_nonlinear_for_mass(payload_mass):
    m2_local = payload_mass
    mtot_local = m1 + m2_local

    def dynamics(t, state):
        xA = state[0]
        xA_dot = state[1]
        theta = state[2]
        theta_dot = state[3]
        error_integral = state[4]
        actuator_1 = state[5]
        actuator_2 = state[6]

        xB = xA + L * np.sin(theta)
        xB_dot = xA_dot + L * np.cos(theta) * theta_dot

        error = reference - xB
        error_dot = -xB_dot

        voltage = Kp * error + Ki * error_integral + Kd * error_dot

        actuator_1_dot = (voltage - actuator_1) / tau1
        actuator_2_dot = (actuator_1 - actuator_2) / tau2

        F = Ka * actuator_2

        M = np.array([
            [mtot_local, m2_local * L * np.cos(theta)],
            [m2_local * L * np.cos(theta), m2_local * L**2]
        ])

        rhs = np.array([
            F - bx * xA_dot + m2_local * L * theta_dot**2 * np.sin(theta),
            -btheta * theta_dot - m2_local * g * L * np.sin(theta)
        ])

        accelerations = np.linalg.solve(M, rhs)

        xA_ddot = accelerations[0]
        theta_ddot = accelerations[1]

        return [
            xA_dot,
            xA_ddot,
            theta_dot,
            theta_ddot,
            error,
            actuator_1_dot,
            actuator_2_dot
        ]

    solution = solve_ivp(
        dynamics,
        [t_start, t_end],
        initial_state,
        t_eval=t_eval,
        rtol=1e-6,
        atol=1e-8
    )

    t_result = solution.t
    xA_result = solution.y[0]
    theta_result = solution.y[2]
    xB_result = xA_result + L * np.sin(theta_result)

    theta_deg_result = theta_result * 180.0 / np.pi
    max_swing = np.max(np.abs(theta_deg_result))
    final_error = reference - xB_result[-1]

    maximum_value = np.max(xB_result)
    overshoot = (maximum_value - reference) / reference * 100

    tolerance = 0.02 * abs(reference)
    within_band = np.abs(xB_result - reference) <= tolerance
    outside_indices = np.where(~within_band)[0]

    if len(outside_indices) == 0:
        settling_time = 0.0
    elif outside_indices[-1] + 1 < len(t_result):
        settling_time = t_result[outside_indices[-1] + 1]
    else:
        settling_time = np.nan

    return t_result, xB_result, max_swing, final_error, overshoot, settling_time


payload_masses = [100.0, 500.0, 1000.0]
robustness_results = {}

plt.figure(figsize=(7, 4))

for mass in payload_masses:
    t_mass, xB_mass, max_swing, final_error, overshoot_mass, settling_time_mass = simulate_nonlinear_for_mass(mass)

    robustness_results[mass] = {
        "max_swing": max_swing,
        "final_error": final_error,
        "overshoot": overshoot_mass,
        "settling_time": settling_time_mass
    }

    plt.plot(t_mass, xB_mass, label=f"m2 = {mass:.0f} kg")

plt.axhline(reference, linestyle="--", label="Reference")
plt.xlabel("Time (s)")
plt.ylabel("Hook position x_B (m)")
plt.title("Robustness test for different payload masses")
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.savefig("robustness_payload_mass.png", dpi=300)
plt.show()

print("\nRobustness test for different payload masses:")
for mass in payload_masses:
    result = robustness_results[mass]
    print(
        f"m2 = {mass:.0f} kg | "
        f"Overshoot = {result['overshoot']:.2f} % | "
        f"Settling time = {result['settling_time']:.2f} s | "
        f"Final error = {result['final_error']:.4f} m | "
        f"Max swing angle = {result['max_swing']:.2f} deg"
    )